controllers:
    resource: ../../src/Controller/
    type: annotation

v1_controllers:
    resource: ../../src/Controller/Api/v1
    type: annotation
    prefix: '/v1'

v2_controllers:
    resource: ../../src/Controller/Api/v2
    type: annotation
    prefix: '/v2'